import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import NAvbar from "../components/navbar"
import Footer from "../components/Footer"

const axiforma = localFont({
  src: [
    {
      path: "../assets/fonts/Axiforma-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Axiforma-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Axiforma-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-axiforma",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${axiforma.variable} antialiased`}
      >
        <NAvbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
